version: '3.8'

services:
  app:
    image: evershop-app:latest
    restart: always
    environment:
      DB_HOST: 10.0.2.4
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: postgres
    ports:
      - 80:3000

networks:
  myevershop:
    name: MyEverShop
    driver: bridge